### ISSUE TITLE
Extension Installs But Doesn't Work

### ISSUE THREAD

**Issue by yannduran** [GregTrevellick/VisualStudioMarketplaceMetrics#1]
Hi Greg,

Great idea! I installed your Chrome extension on both my Surface and my desktop machine. In both cases I can see the button, but instead of being crimson, it's grey. If I click on the button, this is what I get:

![image](https://cloud.githubusercontent.com/assets/2031126/25204858/e7b133f0-25a2-11e7-910c-7e948d9fb8a5.png)

If I click on *Visual Studio Marketplace Metrics*, it just takes me to your github.io website. I've checked that it's enabled:

![image](https://cloud.githubusercontent.com/assets/2031126/25204939/3aa50668-25a3-11e7-979d-65ca45f1243d.png)

I'm not sure what to try.

**Comment by GregTrevellick** [comment]
Hi Yann,

The nature of this extension is that the button is always greyed out unless you are at https://marketplace.visualstudio.com website.

Once you are at https://marketplace.visualstudio.com the button is enabled and should work - that said, I think I've just found a [bug](https://github.com/GregTrevellick/VisualStudioMarketplaceMetrics/issues/2) which occurs when performing a search at the https://marketplace.visualstudio.com site.

Thanks for your feedback, Greg

**Comment by GregTrevellick** [comment]
Yann - the bug I mentioned is now fixed, so let me know if the extension works when visiting https://marketplace.visualstudio.com and I'll close this issue accordingly.

Thanks

**Comment by yannduran** [comment]
Thanks Greg, it's working fine now!
